export const CAPABILITIES = {
  CODE_CONTEXT: [
    "semantic-search",
    "symbol-navigation",
    "call-graph",
    "repo-history",
    "cross-repo-search",
    "structural-search",
    "relationship-graph",
    "impact-analysis",
    "token-efficient-reading",
    "repo-snapshot",
  ],
  DOCS: [
    "package-docs",
    "repository-docs",
    "source-inspection",
    "framework-docs",
    "api-reference",
  ],
  UI: [
    "design-system",
    "component-registry",
    "browser-test",
    "browser-debug",
    "react-runtime",
    "accessibility",
    "performance",
    "design-to-code",
  ],
  MOBILE: [
    "framework-analysis",
    "framework-docs",
    "runtime-inspection",
    "component-tree",
    "emulator-control",
    "native-dialog-control",
    "e2e-device-test",
    "hot-reload",
    "logs",
    "performance",
    "build-release",
    "app-distribution",
  ],
  API: ["api-contract", "api-client", "mocking", "graphql", "api-testing"],
  SECURITY: [
    "sast",
    "dependency-risk",
    "quality-analysis",
    "secret-safety",
    "sql-safety",
  ],
  DATA: ["generic-sql", "schema-inspection", "migrations", "supabase", "neon"],
  OPS: [
    "deployment",
    "observability",
    "production-errors",
    "kubernetes",
    "terraform",
    "git-hosting",
    "ci",
    "release",
  ],
} as const;

export const ALL_CAPABILITIES = Object.entries(CAPABILITIES).flatMap(
  ([group, values]) => values.map((value) => `${group}.${value}`),
);
