import {
  capabilityCandidateSchema,
  type CapabilityCandidate,
  type CapabilityKind,
  type Permissions,
  type Scope,
  type TrustTier,
} from "@loom/core";

type RuntimeKind = NonNullable<CapabilityCandidate["runtime"]>["kind"];

export const CATALOG_CATEGORIES = [
  "code-intelligence",
  "documentation",
  "web-ui",
  "mobile",
  "api",
  "security",
  "data",
  "operations",
  "frameworks",
] as const;

export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number];

export interface CatalogSection {
  category: CatalogCategory;
  label: string;
  candidates: readonly CapabilityCandidate[];
}

interface Seed {
  id: string;
  name: string;
  kind: CapabilityKind;
  provides: string[];
  ecosystems: string[];
  triggers: string[];
  overlap: string[];
  trust: TrustTier;
  scope: Scope;
  runtime?: RuntimeKind;
  repository?: string;
  package?: string;
  version?: string;
  permissions?: Partial<Permissions>;
  notes?: string[];
}

const basePermissions: Permissions = {
  filesystem: "read",
  shell: false,
  network: false,
  secrets: [],
  database: "none",
  device: false,
};

const seed = (value: Seed): CapabilityCandidate =>
  capabilityCandidateSchema.parse({
    id: `builtin:${value.id}`,
    name: value.name,
    kind: value.kind,
    source: {
      registry: "builtin",
      ...(value.repository === undefined
        ? {}
        : { repository: value.repository }),
      ...(value.package === undefined ? {} : { package: value.package }),
    },
    ...(value.version === undefined ? {} : { version: value.version }),
    ecosystems: value.ecosystems,
    provides: value.provides,
    tags: [...new Set([...value.ecosystems, ...value.triggers])],
    ...(value.kind === "mcp"
      ? { transport: value.runtime === "remote" ? "http" : "stdio" }
      : {}),
    ...(value.runtime === undefined
      ? {}
      : {
          runtime: {
            kind: value.runtime,
            ...(value.package === undefined ? {} : { command: value.package }),
          },
        }),
    permissions: { ...basePermissions, ...value.permissions },
    provenance: {
      official: value.trust === "official",
      namespaceVerified: value.trust === "official",
      knownMaintainer: ["official", "verified-maintainer"].includes(
        value.trust,
      ),
      repositoryVerified: value.repository !== undefined,
    },
    overlapGroups: value.overlap,
    recommendedScope: value.scope,
    trustTier: value.trust,
    taskTriggers: value.triggers,
    contextCost: value.kind === "mcp" ? 30 : 12,
    portability: value.runtime === "remote" ? 75 : 60,
    notes: value.notes ?? [],
  });

const github = (path: string): string => `https://github.com/${path}`;
const remote = {
  network: true,
  secrets: ["service-api-key"],
} satisfies Partial<Permissions>;
const shell = {
  shell: true,
  filesystem: "write",
} satisfies Partial<Permissions>;
const device = {
  shell: true,
  filesystem: "write",
  device: true,
} satisfies Partial<Permissions>;
const database = {
  network: true,
  database: "read",
  secrets: ["database-url"],
} satisfies Partial<Permissions>;

const seeds: Seed[] = [
  // Code intelligence
  {
    id: "codanna",
    name: "Codanna",
    kind: "mcp",
    provides: [
      "CODE_CONTEXT.semantic-search",
      "CODE_CONTEXT.symbol-navigation",
      "CODE_CONTEXT.call-graph",
      "CODE_CONTEXT.impact-analysis",
    ],
    ecosystems: ["code"],
    triggers: ["brownfield", "large-repository"],
    overlap: ["code-intelligence"],
    trust: "community-reviewed",
    scope: "project",
    runtime: "binary",
    repository: github("bartolli/codanna"),
  },
  {
    id: "codegraphy",
    name: "CodeGraphy",
    kind: "mcp",
    provides: [
      "CODE_CONTEXT.relationship-graph",
      "CODE_CONTEXT.impact-analysis",
    ],
    ecosystems: ["code"],
    triggers: ["architecture", "workspace-map"],
    overlap: ["code-intelligence"],
    trust: "community",
    scope: "project",
    runtime: "node",
  },
  {
    id: "serena",
    name: "Serena",
    kind: "mcp",
    provides: [
      "CODE_CONTEXT.semantic-search",
      "CODE_CONTEXT.symbol-navigation",
      "CODE_CONTEXT.impact-analysis",
    ],
    ecosystems: ["code", "lsp"],
    triggers: ["targeted-edit", "brownfield"],
    overlap: ["code-intelligence"],
    trust: "community-reviewed",
    scope: "project",
    runtime: "python",
    repository: github("oraios/serena"),
    permissions: shell,
    notes: ["Can modify project files"],
  },
  {
    id: "rag-rat",
    name: "rag-rat",
    kind: "mcp",
    provides: ["CODE_CONTEXT.repo-history"],
    ecosystems: ["git", "github"],
    triggers: ["history", "why-code-exists"],
    overlap: ["repository-history"],
    trust: "community",
    scope: "project",
    runtime: "node",
    permissions: { network: true },
  },
  {
    id: "tearags",
    name: "TeaRAGs",
    kind: "mcp",
    provides: [
      "CODE_CONTEXT.semantic-search",
      "CODE_CONTEXT.repo-history",
      "CODE_CONTEXT.impact-analysis",
    ],
    ecosystems: ["git"],
    triggers: ["ownership", "churn", "reuse"],
    overlap: ["code-intelligence", "repository-history"],
    trust: "community",
    scope: "project",
    runtime: "python",
  },
  {
    id: "srag",
    name: "srag",
    kind: "mcp",
    provides: [
      "CODE_CONTEXT.cross-repo-search",
      "CODE_CONTEXT.semantic-search",
    ],
    ecosystems: ["git"],
    triggers: ["cross-repository", "project-memory"],
    overlap: ["cross-repo-search"],
    trust: "community",
    scope: "global",
    runtime: "python",
  },
  {
    id: "ast-grep",
    name: "ast-grep",
    kind: "cli",
    provides: ["CODE_CONTEXT.structural-search", "SECURITY.sast"],
    ecosystems: ["code"],
    triggers: ["codemod", "migration", "refactor"],
    overlap: ["structural-search"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "binary",
    repository: github("ast-grep/ast-grep"),
    package: "ast-grep",
    permissions: shell,
  },
  {
    id: "pluck",
    name: "pluck",
    kind: "cli",
    provides: [
      "CODE_CONTEXT.token-efficient-reading",
      "CODE_CONTEXT.symbol-navigation",
      "CODE_CONTEXT.impact-analysis",
    ],
    ecosystems: ["code"],
    triggers: ["large-file", "peek"],
    overlap: ["code-reading"],
    trust: "community",
    scope: "project",
    runtime: "binary",
  },
  {
    id: "repomix",
    name: "Repomix",
    kind: "cli",
    provides: [
      "CODE_CONTEXT.repo-snapshot",
      "CODE_CONTEXT.token-efficient-reading",
    ],
    ecosystems: ["code", "git"],
    triggers: ["architecture-review", "context-pack"],
    overlap: ["repository-snapshot"],
    trust: "verified-maintainer",
    scope: "on-demand",
    runtime: "node",
    repository: github("yamadashy/repomix"),
    package: "repomix",
    permissions: { filesystem: "write" },
  },

  {
    id: "context7",
    name: "Context7",
    kind: "mcp",
    provides: [
      "DOCS.package-docs",
      "DOCS.framework-docs",
      "DOCS.api-reference",
    ],
    ecosystems: ["packages"],
    triggers: ["current-documentation"],
    overlap: ["documentation"],
    trust: "verified-maintainer",
    scope: "on-demand",
    runtime: "remote",
    permissions: remote,
  },
  {
    id: "gitmcp",
    name: "GitMCP",
    kind: "mcp",
    provides: ["DOCS.repository-docs", "DOCS.source-inspection"],
    ecosystems: ["github"],
    triggers: ["unfamiliar-dependency"],
    overlap: ["repository-docs"],
    trust: "community-reviewed",
    scope: "on-demand",
    runtime: "remote",
    repository: github("idosal/git-mcp"),
    permissions: { network: true },
  },
  {
    id: "deepwiki",
    name: "DeepWiki",
    kind: "mcp",
    provides: ["DOCS.repository-docs"],
    ecosystems: ["github"],
    triggers: ["architecture-docs"],
    overlap: ["repository-docs"],
    trust: "community",
    scope: "on-demand",
    runtime: "remote",
    permissions: { network: true },
  },
  {
    id: "opensrc",
    name: "opensrc",
    kind: "cli",
    provides: ["DOCS.source-inspection", "DOCS.package-docs"],
    ecosystems: ["npm", "open-source"],
    triggers: ["dependency-source"],
    overlap: ["source-inspection"],
    trust: "verified-maintainer",
    scope: "on-demand",
    runtime: "node",
    repository: github("vercel-labs/opensrc"),
    package: "opensrc",
    permissions: { network: true, filesystem: "write" },
  },

  {
    id: "agent-browser",
    name: "agent-browser",
    kind: "mcp",
    provides: [
      "UI.browser-test",
      "UI.browser-debug",
      "UI.react-runtime",
      "UI.accessibility",
      "UI.performance",
    ],
    ecosystems: ["web", "react"],
    triggers: ["browser", "ui-test"],
    overlap: ["browser-control"],
    trust: "verified-maintainer",
    scope: "on-demand",
    runtime: "node",
    repository: github("vercel-labs/agent-browser"),
    permissions: { ...device, network: true },
  },
  {
    id: "web-agent-intelligence",
    name: "Web agent intelligence",
    kind: "mcp",
    provides: [
      "UI.browser-test",
      "UI.browser-debug",
      "UI.accessibility",
      "DOCS.source-inspection",
    ],
    ecosystems: ["web", "react", "nextjs", "vite", "astro", "typescript"],
    triggers: ["browser", "ui-test", "dependency-source"],
    overlap: ["browser-control", "source-inspection"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "node",
    repository: github("vercel-labs/agent-browser"),
    package: "agent-browser",
    version: "0.34.0",
    permissions: {
      filesystem: "write",
      shell: true,
      network: true,
      device: true,
    },
    notes: ["Audited project recipe with pinned packages and isolated state."],
  },
  {
    id: "chrome-devtools-mcp",
    name: "Chrome DevTools MCP",
    kind: "mcp",
    provides: ["UI.browser-debug", "UI.performance", "UI.react-runtime"],
    ecosystems: ["web", "chrome"],
    triggers: ["network-debug", "performance-trace"],
    overlap: ["browser-control", "browser-debug"],
    trust: "official",
    scope: "on-demand",
    runtime: "node",
    permissions: { ...device, network: true },
  },
  {
    id: "storybook-mcp",
    name: "Storybook MCP",
    kind: "mcp",
    provides: [
      "UI.component-registry",
      "UI.design-system",
      "UI.accessibility",
      "UI.browser-test",
    ],
    ecosystems: ["storybook", "web"],
    triggers: ["stories", "component-api"],
    overlap: ["component-registry"],
    trust: "official",
    scope: "project",
    runtime: "node",
    permissions: { network: true },
  },
  {
    id: "shadcn-mcp",
    name: "shadcn MCP",
    kind: "mcp",
    provides: ["UI.component-registry", "UI.design-system"],
    ecosystems: ["shadcn", "react"],
    triggers: ["components-json"],
    overlap: ["component-registry"],
    trust: "official",
    scope: "project",
    runtime: "node",
    permissions: { ...shell, network: true },
  },
  {
    id: "widgetbook",
    name: "Widgetbook",
    kind: "framework-tool",
    provides: ["UI.component-registry", "UI.design-system"],
    ecosystems: ["flutter", "dart"],
    triggers: ["widgetbook", "component-catalog"],
    overlap: ["component-registry"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "dart",
    permissions: shell,
  },
  {
    id: "agent-react-devtools",
    name: "agent-react-devtools",
    kind: "mcp",
    provides: [
      "UI.react-runtime",
      "MOBILE.component-tree",
      "MOBILE.runtime-inspection",
      "UI.performance",
    ],
    ecosystems: ["react", "react-native", "expo"],
    triggers: ["props", "state", "rerender"],
    overlap: ["react-runtime"],
    trust: "community-reviewed",
    scope: "on-demand",
    runtime: "node",
    repository: github("callstackincubator/agent-react-devtools"),
    permissions: { network: true, device: true },
  },
  {
    id: "figma-mcp",
    name: "Figma MCP",
    kind: "mcp",
    provides: ["UI.design-to-code", "UI.design-system"],
    ecosystems: ["figma", "ui"],
    triggers: ["figma-url", "code-connect"],
    overlap: ["design-to-code"],
    trust: "official",
    scope: "on-demand",
    runtime: "remote",
    permissions: remote,
  },
  {
    id: "ui-ux-pro-max",
    name: "UI UX Pro Max",
    kind: "skill",
    provides: ["UI.design-system"],
    ecosystems: ["ui"],
    triggers: ["design-synthesis", "ux-guidance"],
    overlap: ["design-guidance"],
    trust: "community-reviewed",
    scope: "project",
    repository: github("nextlevelbuilder/ui-ux-pro-max-skill"),
  },
  {
    id: "awesome-design-md",
    name: "Awesome DESIGN.md",
    kind: "skill",
    provides: ["UI.design-system"],
    ecosystems: ["ui"],
    triggers: ["design-reference"],
    overlap: ["design-guidance"],
    trust: "community-reviewed",
    scope: "on-demand",
    repository: github("VoltAgent/awesome-design-md"),
  },
  {
    id: "21st-mcp",
    name: "21st MCP",
    kind: "mcp",
    provides: ["UI.component-registry", "UI.design-to-code"],
    ecosystems: ["web", "ui"],
    triggers: ["component-inspiration", "theme"],
    overlap: ["component-registry", "design-to-code"],
    trust: "community",
    scope: "on-demand",
    runtime: "remote",
    permissions: remote,
  },
  {
    id: "axe-accessibility",
    name: "axe accessibility",
    kind: "cli",
    provides: ["UI.accessibility"],
    ecosystems: ["web"],
    triggers: ["a11y", "remediation"],
    overlap: ["accessibility-audit"],
    trust: "verified-maintainer",
    scope: "on-demand",
    runtime: "node",
    permissions: { network: true },
  },
  {
    id: "lighthouse",
    name: "Lighthouse",
    kind: "cli",
    provides: ["UI.performance", "UI.accessibility"],
    ecosystems: ["web", "chrome"],
    triggers: ["performance-audit", "seo"],
    overlap: ["web-audit"],
    trust: "official",
    scope: "on-demand",
    runtime: "node",
    permissions: { network: true, device: true },
  },

  {
    id: "flutter-package-intelligence",
    name: "Flutter Package Intelligence",
    kind: "plugin",
    provides: [
      "MOBILE.framework-analysis",
      "MOBILE.framework-docs",
      "MOBILE.runtime-inspection",
      "MOBILE.hot-reload",
      "MOBILE.logs",
      "DOCS.package-docs",
      "DOCS.source-inspection",
      "SECURITY.dependency-risk",
    ],
    ecosystems: ["flutter", "dart"],
    triggers: ["flutter-development", "package-skills", "pub-dev"],
    overlap: ["flutter-framework", "dart-runtime"],
    trust: "official",
    scope: "project",
    runtime: "dart",
    repository: github("PhilippHGerber/agentic_dart"),
    version: "0.9.0+skills.1.0.0",
    permissions: { ...device, network: true },
  },
  {
    id: "dart-flutter-mcp",
    name: "Dart / Flutter MCP",
    kind: "framework-tool",
    provides: ["MOBILE.hot-reload", "MOBILE.logs"],
    ecosystems: ["flutter", "dart"],
    triggers: ["analysis", "tests", "runtime"],
    overlap: ["dart-runtime"],
    trust: "official",
    scope: "on-demand",
    runtime: "dart",
    package: "dart mcp-server",
    version: "project-sdk",
    permissions: { ...device, network: true },
  },
  {
    id: "patrol-mcp",
    name: "Patrol MCP",
    kind: "mcp",
    provides: [
      "MOBILE.e2e-device-test",
      "MOBILE.native-dialog-control",
      "MOBILE.logs",
    ],
    ecosystems: ["flutter", "dart"],
    triggers: ["integration-test", "permission-dialog"],
    overlap: ["mobile-e2e"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "dart",
    repository: github("leancodepl/patrol"),
    permissions: device,
  },
  {
    id: "marionette-mcp",
    name: "Marionette MCP",
    kind: "mcp",
    provides: [
      "MOBILE.runtime-inspection",
      "MOBILE.component-tree",
      "MOBILE.emulator-control",
    ],
    ecosystems: ["flutter", "dart"],
    triggers: ["interactive-exploration", "widget-inspection"],
    overlap: ["flutter-runtime", "device-control"],
    trust: "community-reviewed",
    scope: "on-demand",
    runtime: "dart",
    repository: github("leancodepl/marionette_mcp"),
    permissions: device,
  },
  {
    id: "dusk",
    name: "Dusk",
    kind: "mcp",
    provides: ["MOBILE.runtime-inspection", "MOBILE.component-tree"],
    ecosystems: ["flutter", "dart"],
    triggers: ["widget-tree", "runtime-observation"],
    overlap: ["flutter-runtime"],
    trust: "experimental",
    scope: "on-demand",
    runtime: "dart",
    repository: github("fluttersdk/dusk"),
    permissions: device,
  },
  {
    id: "maestro-mcp",
    name: "Maestro MCP",
    kind: "mcp",
    provides: [
      "MOBILE.e2e-device-test",
      "MOBILE.emulator-control",
      "MOBILE.native-dialog-control",
    ],
    ecosystems: ["flutter", "react-native", "android", "ios"],
    triggers: ["device-flow", "black-box-e2e"],
    overlap: ["mobile-e2e", "device-control"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "binary",
    permissions: device,
  },
  {
    id: "mobile-mcp",
    name: "Mobile MCP",
    kind: "mcp",
    provides: ["MOBILE.emulator-control", "MOBILE.runtime-inspection"],
    ecosystems: ["android", "ios", "flutter", "react-native"],
    triggers: ["tap", "type", "screenshot"],
    overlap: ["device-control"],
    trust: "community-reviewed",
    scope: "on-demand",
    runtime: "node",
    repository: github("mobile-next/mobile-mcp"),
    permissions: device,
  },
  {
    id: "appium-mcp",
    name: "Appium MCP",
    kind: "mcp",
    provides: [
      "MOBILE.e2e-device-test",
      "MOBILE.emulator-control",
      "MOBILE.native-dialog-control",
    ],
    ecosystems: ["android", "ios", "hybrid"],
    triggers: ["appium", "device-lab"],
    overlap: ["mobile-e2e", "device-control"],
    trust: "official",
    scope: "project",
    runtime: "node",
    repository: github("appium/appium-mcp"),
    permissions: device,
  },
  {
    id: "device-mcp",
    name: "device-mcp",
    kind: "mcp",
    provides: ["MOBILE.e2e-device-test", "MOBILE.emulator-control"],
    ecosystems: ["android", "ios", "appium", "browserstack"],
    triggers: ["device-testing"],
    overlap: ["mobile-e2e", "device-control"],
    trust: "verified-maintainer",
    scope: "on-demand",
    runtime: "node",
    repository: github("MetaMask/device-mcp"),
    permissions: { ...device, network: true, secrets: ["browserstack-token"] },
  },
  {
    id: "expo-skills",
    name: "Expo skills",
    kind: "skill",
    provides: [
      "MOBILE.framework-analysis",
      "MOBILE.framework-docs",
      "MOBILE.build-release",
      "MOBILE.app-distribution",
    ],
    ecosystems: ["expo"],
    triggers: ["expo-router", "eas"],
    overlap: ["expo-framework"],
    trust: "official",
    scope: "project",
    repository: github("expo/skills"),
  },
  {
    id: "expo-mcp",
    name: "Expo MCP",
    kind: "mcp",
    provides: [
      "MOBILE.framework-analysis",
      "MOBILE.framework-docs",
      "MOBILE.emulator-control",
      "MOBILE.build-release",
      "MOBILE.app-distribution",
    ],
    ecosystems: ["expo"],
    triggers: ["eas", "simulator"],
    overlap: ["expo-framework", "device-control"],
    trust: "official",
    scope: "project",
    runtime: "node",
    repository: github("expo/skills"),
    permissions: { ...device, network: true, secrets: ["expo-token"] },
  },
  {
    id: "callstack-rn-skills",
    name: "Callstack React Native agent skills",
    kind: "skill",
    provides: ["MOBILE.framework-analysis", "MOBILE.performance"],
    ecosystems: ["react-native"],
    triggers: ["jank", "hermes", "memory", "rerender"],
    overlap: ["react-native-guidance"],
    trust: "verified-maintainer",
    scope: "project",
    repository: github("callstackincubator/agent-skills"),
  },
  {
    id: "vercel-rn-skills",
    name: "Vercel React Native skills",
    kind: "skill",
    provides: ["MOBILE.framework-analysis", "MOBILE.framework-docs"],
    ecosystems: ["react-native"],
    triggers: ["navigation", "state", "animations", "monorepo"],
    overlap: ["react-native-guidance"],
    trust: "verified-maintainer",
    scope: "project",
  },
  {
    id: "react-native-mcp-community",
    name: "React Native MCP community candidates",
    kind: "mcp",
    provides: ["MOBILE.runtime-inspection"],
    ecosystems: ["react-native"],
    triggers: ["dynamic-discovery"],
    overlap: ["react-native-runtime"],
    trust: "experimental",
    scope: "on-demand",
    runtime: "node",
    permissions: device,
    notes: [
      "Placeholder for dynamically discovered and reviewed implementations",
    ],
  },

  {
    id: "postman-mcp",
    name: "Postman MCP",
    kind: "mcp",
    provides: ["API.api-contract", "API.api-client", "API.api-testing"],
    ecosystems: ["postman", "openapi"],
    triggers: ["collection", "api-test"],
    overlap: ["api-client"],
    trust: "official",
    scope: "project",
    runtime: "remote",
    permissions: remote,
  },
  {
    id: "mockoon-mcp",
    name: "Mockoon MCP",
    kind: "mcp",
    provides: ["API.mocking"],
    ecosystems: ["api", "openapi"],
    triggers: ["local-mock", "frontend-first"],
    overlap: ["api-mocking"],
    trust: "official",
    scope: "project",
    runtime: "node",
    permissions: { ...shell, network: true },
  },
  {
    id: "wiremock",
    name: "WireMock",
    kind: "framework-tool",
    provides: ["API.mocking", "API.api-contract", "API.api-testing"],
    ecosystems: ["java", "openapi", "api"],
    triggers: ["fault-injection", "recording"],
    overlap: ["api-mocking"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "binary",
    permissions: { ...shell, network: true },
  },
  {
    id: "apollo-mcp",
    name: "Apollo MCP",
    kind: "mcp",
    provides: ["API.graphql", "API.api-contract", "API.api-testing"],
    ecosystems: ["graphql", "apollo"],
    triggers: ["graphql-schema"],
    overlap: ["graphql-tooling"],
    trust: "official",
    scope: "project",
    runtime: "node",
    permissions: { network: true, secrets: ["apollo-key"] },
  },

  {
    id: "socket-mcp",
    name: "Socket MCP",
    kind: "mcp",
    provides: ["SECURITY.dependency-risk", "SECURITY.quality-analysis"],
    ecosystems: ["packages", "npm"],
    triggers: ["supply-chain", "pre-install-review"],
    overlap: ["dependency-security"],
    trust: "verified-maintainer",
    scope: "on-demand",
    runtime: "node",
    repository: github("SocketDev/socket-mcp"),
    permissions: { network: true, secrets: ["socket-token"] },
  },
  {
    id: "semgrep",
    name: "Semgrep",
    kind: "cli",
    provides: ["SECURITY.sast", "SECURITY.secret-safety"],
    ecosystems: ["code"],
    triggers: ["security-review", "ast-rule"],
    overlap: ["sast"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "python",
    permissions: { filesystem: "read" },
  },
  {
    id: "sonarqube-mcp",
    name: "SonarQube MCP",
    kind: "mcp",
    provides: ["SECURITY.quality-analysis", "SECURITY.sast"],
    ecosystems: ["sonarqube", "sonarcloud"],
    triggers: ["quality-gate"],
    overlap: ["sast", "quality-analysis"],
    trust: "official",
    scope: "project",
    runtime: "remote",
    permissions: remote,
  },
  {
    id: "sql-safety",
    name: "SQL safety candidate",
    kind: "cli",
    provides: ["SECURITY.sql-safety"],
    ecosystems: ["sql"],
    triggers: ["database-write", "migration-review"],
    overlap: ["sql-safety"],
    trust: "experimental",
    scope: "on-demand",
    permissions: { database: "read" },
    notes: ["Discovery placeholder; database writes remain disabled"],
  },

  {
    id: "dbhub",
    name: "DBHub",
    kind: "mcp",
    provides: ["DATA.generic-sql", "DATA.schema-inspection"],
    ecosystems: ["postgresql", "mysql", "mariadb", "sqlserver", "sqlite"],
    triggers: ["schema", "sql"],
    overlap: ["database-access"],
    trust: "verified-maintainer",
    scope: "project",
    runtime: "node",
    repository: github("bytebase/dbhub"),
    permissions: database,
    notes: ["Default to read-only connections"],
  },
  {
    id: "supabase-mcp",
    name: "Supabase MCP",
    kind: "mcp",
    provides: [
      "DATA.supabase",
      "DATA.schema-inspection",
      "DATA.migrations",
      "MOBILE.logs",
    ],
    ecosystems: ["supabase", "postgresql"],
    triggers: ["supabase-config", "types"],
    overlap: ["database-access", "supabase-platform"],
    trust: "official",
    scope: "project",
    runtime: "remote",
    permissions: { ...database, secrets: ["supabase-token"] },
  },
  {
    id: "neon-mcp",
    name: "Neon MCP",
    kind: "mcp",
    provides: ["DATA.neon", "DATA.schema-inspection", "DATA.migrations"],
    ecosystems: ["neon", "postgresql"],
    triggers: ["database-branch", "development-migration"],
    overlap: ["database-access", "neon-platform"],
    trust: "official",
    scope: "project",
    runtime: "remote",
    permissions: { ...database, secrets: ["neon-token"] },
    notes: ["Never target production automatically"],
  },

  {
    id: "github-mcp",
    name: "GitHub MCP",
    kind: "mcp",
    provides: [
      "OPS.git-hosting",
      "OPS.ci",
      "OPS.release",
      "SECURITY.dependency-risk",
    ],
    ecosystems: ["github", "git"],
    triggers: ["pull-request", "issue", "actions"],
    overlap: ["git-hosting"],
    trust: "official",
    scope: "on-demand",
    runtime: "remote",
    permissions: { network: true, secrets: ["github-token"] },
  },
  {
    id: "vercel-mcp",
    name: "Vercel MCP",
    kind: "mcp",
    provides: ["OPS.deployment", "OPS.observability", "DOCS.framework-docs"],
    ecosystems: ["vercel", "next.js"],
    triggers: ["vercel-json", "deployment"],
    overlap: ["deployment-platform"],
    trust: "official",
    scope: "project",
    runtime: "remote",
    permissions: { network: true, secrets: ["vercel-token"] },
  },
  {
    id: "cloudflare-mcp",
    name: "Cloudflare MCP",
    kind: "mcp",
    provides: ["OPS.deployment", "OPS.observability", "DOCS.framework-docs"],
    ecosystems: ["cloudflare", "workers"],
    triggers: ["wrangler", "worker"],
    overlap: ["deployment-platform"],
    trust: "official",
    scope: "project",
    runtime: "remote",
    permissions: { network: true, secrets: ["cloudflare-token"] },
  },
  {
    id: "sentry-mcp",
    name: "Sentry MCP",
    kind: "mcp",
    provides: ["OPS.production-errors", "OPS.observability"],
    ecosystems: ["sentry"],
    triggers: ["stack-trace", "production-issue"],
    overlap: ["observability"],
    trust: "official",
    scope: "on-demand",
    runtime: "remote",
    permissions: { network: true, secrets: ["sentry-token"] },
  },
  {
    id: "grafana-mcp",
    name: "Grafana MCP",
    kind: "mcp",
    provides: ["OPS.observability", "OPS.production-errors"],
    ecosystems: ["grafana", "prometheus", "loki"],
    triggers: ["metrics", "logs"],
    overlap: ["observability"],
    trust: "official",
    scope: "on-demand",
    runtime: "remote",
    permissions: { network: true, secrets: ["grafana-token"] },
  },
  {
    id: "datadog-mcp",
    name: "Datadog MCP",
    kind: "mcp",
    provides: ["OPS.observability", "OPS.production-errors"],
    ecosystems: ["datadog"],
    triggers: ["metrics", "traces"],
    overlap: ["observability"],
    trust: "official",
    scope: "on-demand",
    runtime: "remote",
    permissions: { network: true, secrets: ["datadog-api-key"] },
  },
  {
    id: "kubernetes-mcp",
    name: "Kubernetes MCP",
    kind: "mcp",
    provides: ["OPS.kubernetes", "OPS.deployment", "OPS.observability"],
    ecosystems: ["kubernetes", "helm"],
    triggers: ["cluster", "manifest"],
    overlap: ["infrastructure-control"],
    trust: "community-reviewed",
    scope: "project",
    runtime: "binary",
    permissions: { ...shell, network: true, secrets: ["kubeconfig"] },
    notes: ["Default to read-only cluster access"],
  },
  {
    id: "terraform-mcp",
    name: "Terraform MCP",
    kind: "mcp",
    provides: ["OPS.terraform", "OPS.deployment"],
    ecosystems: ["terraform", "iac"],
    triggers: ["tf-file", "infrastructure"],
    overlap: ["infrastructure-control"],
    trust: "official",
    scope: "project",
    runtime: "binary",
    permissions: { ...shell, network: true, secrets: ["cloud-credentials"] },
  },
  {
    id: "docker-mcp-gateway",
    name: "Docker MCP Gateway",
    kind: "framework-tool",
    provides: ["OPS.deployment"],
    ecosystems: ["docker", "mcp"],
    triggers: ["sandbox", "runtime-isolation"],
    overlap: ["mcp-runtime"],
    trust: "official",
    scope: "global",
    runtime: "docker",
    permissions: { ...shell, network: true, secrets: ["runtime-credentials"] },
  },

  {
    id: "laravel-boost",
    name: "Laravel Boost",
    kind: "framework-tool",
    provides: [
      "DOCS.framework-docs",
      "DATA.schema-inspection",
      "OPS.production-errors",
    ],
    ecosystems: ["laravel", "php"],
    triggers: ["artisan", "laravel-framework"],
    overlap: ["laravel-framework"],
    trust: "official",
    scope: "project",
    runtime: "binary",
    permissions: { ...shell, database: "read" },
  },
  {
    id: "laravel-agent-skills",
    name: "Laravel Agent Skills",
    kind: "skill",
    provides: ["DOCS.framework-docs", "OPS.deployment", "OPS.observability"],
    ecosystems: ["laravel", "php"],
    triggers: ["upgrade", "laravel-cloud", "nightwatch"],
    overlap: ["laravel-guidance"],
    trust: "official",
    scope: "project",
    repository: github("laravel/agent-skills"),
  },
  {
    id: "nightwatch-mcp",
    name: "Nightwatch MCP",
    kind: "mcp",
    provides: ["OPS.production-errors", "OPS.observability"],
    ecosystems: ["laravel", "nightwatch"],
    triggers: ["production-issue"],
    overlap: ["observability"],
    trust: "official",
    scope: "on-demand",
    runtime: "remote",
    permissions: { network: true, secrets: ["nightwatch-token"] },
  },
  {
    id: "laravel-cloud",
    name: "Laravel Cloud skill/tooling",
    kind: "skill",
    provides: ["OPS.deployment", "OPS.observability"],
    ecosystems: ["laravel", "laravel-cloud"],
    triggers: ["cloud-deployment"],
    overlap: ["deployment-platform"],
    trust: "official",
    scope: "project",
  },
  {
    id: "laravel-mcp-framework",
    name: "Laravel MCP framework",
    kind: "framework-tool",
    provides: ["API.api-contract"],
    ecosystems: ["laravel", "php", "mcp"],
    triggers: ["product-mcp-requirement"],
    overlap: ["mcp-framework"],
    trust: "official",
    scope: "project",
    runtime: "binary",
    repository: github("laravel/mcp"),
    permissions: shell,
    notes: ["Only for products that expose or consume MCP"],
  },
  {
    id: "laravel-ai-sdk",
    name: "Laravel AI SDK",
    kind: "framework-tool",
    provides: ["DOCS.framework-docs", "API.api-client"],
    ecosystems: ["laravel", "php", "ai"],
    triggers: ["ai-agent-package"],
    overlap: ["laravel-ai"],
    trust: "official",
    scope: "project",
    runtime: "binary",
    permissions: { ...shell, network: true, secrets: ["model-provider-key"] },
  },
  {
    id: "gopls-mcp",
    name: "gopls MCP",
    kind: "framework-tool",
    provides: [
      "CODE_CONTEXT.symbol-navigation",
      "CODE_CONTEXT.call-graph",
      "DOCS.framework-docs",
    ],
    ecosystems: ["go", "gopls"],
    triggers: ["go-mod", "language-semantics"],
    overlap: ["go-language-server", "code-intelligence"],
    trust: "official",
    scope: "project",
    runtime: "go",
    permissions: { filesystem: "write" },
  },
];

const categoryFor = (candidate: CapabilityCandidate): CatalogCategory => {
  if (
    candidate.ecosystems.some((value) =>
      ["flutter", "dart", "react-native", "expo", "mobile"].includes(value),
    )
  )
    return "mobile";
  if (
    candidate.ecosystems.some((value) =>
      ["laravel", "php", "go", "gopls"].includes(value),
    )
  )
    return "frameworks";
  const namespaces = new Set(
    candidate.provides.map((capability) => capability.split(".")[0]),
  );
  if (namespaces.has("UI")) return "web-ui";
  if (namespaces.has("API")) return "api";
  if (namespaces.has("SECURITY")) return "security";
  if (namespaces.has("DATA")) return "data";
  if (namespaces.has("OPS")) return "operations";
  if (namespaces.has("DOCS")) return "documentation";
  return "code-intelligence";
};

const categoryLabels: Record<CatalogCategory, string> = {
  "code-intelligence": "Code intelligence",
  documentation: "Documentation and source context",
  "web-ui": "Web and UI",
  mobile: "Flutter, Dart, and mobile",
  api: "API and testing",
  security: "Security and quality",
  data: "Data and databases",
  operations: "Operations and deployment",
  frameworks: "Framework-specific tooling",
};

export const BUILTIN_CATALOG: readonly CapabilityCandidate[] = seeds.map(seed);

export const BUILTIN_CATALOG_SECTIONS: readonly CatalogSection[] =
  CATALOG_CATEGORIES.map((category) => ({
    category,
    label: categoryLabels[category],
    candidates: BUILTIN_CATALOG.filter(
      (candidate) => categoryFor(candidate) === category,
    ),
  })).filter((section) => section.candidates.length > 0);
